# config.py

# --- 模拟与算法参数 ---
NUM_ZONES = 5        # 分区数量 (论文中的 k_n)
CITY_NAME = "Chengdu"

# --- 地理位置参数 ---
# 成都市中心坐标 (用于 OSMnx 下载)
# 对应论文图 3 的大致中心位置 (纬度, 经度)
CHENGDU_CENTER = (30.67, 104.06)

# 下载半径 (米)
# 之前的 2000 米可能略大，如果为了测试速度可以改小，比如 1000
DOWNLOAD_DIST = 5000

# --- 绘图配置 ---
# 颜色映射风格
COLOR_MAP = 'tab10'
# --- 配送经济学与物理学参数设定 ---

# --- 预测模块参数 ---
# 将需求预测网格与多中心分区数量解耦，避免修改 NUM_ZONES 时静默影响预测实验。
PRED_GRID_SIZE = (5, 5)

# 1. 物理参数
WORKER_SPEED_KMH = 12              # 骑手平均行驶速度 (18 km/h，考虑了红绿灯和市区路况)
WORKER_SPEED_MS = WORKER_SPEED_KMH / 3.6 # 换算为米/秒 (约 5.0 m/s)

# 2. 经济参数 (单位: 元 RMB)
TASK_BASE_REWARD = 8.0                # 每成功送达一单的固定奖励 (8元/单)
TRAVEL_COST_PER_KM = 0.5              # 骑手行驶成本 (0.5元/公里，包含电费、车辆折旧、体力成本折算)
TRAVEL_COST_PER_METER = TRAVEL_COST_PER_KM / 1000.0 # 换算为每米成本 (0.0005元/米)

# 3. 惩罚参数 (用于高级算法中的成本核算)
DELAY_PENALTY = 5.0                   # 订单超时/无法分配的系统声誉损失惩罚 (5元/单)
TASK_EXPIRE_MINUTES = 10

# 4. 在线模拟实验配置
EXPERIMENT_TEST_DATE = "2016-11-30"  # 默认实验日期
EXPERIMENT_START_HOUR = 7             # 默认实验开始时间（小时）
EXPERIMENT_END_HOUR = 9               # 默认实验结束时间（小时）
EXPERIMENT_TIME_SLOT_MINUTES = 15     # 默认时间槽长度（分钟）
WORKER_INIT_PREP_MINUTES = 5          # 初始化工人位置时回看历史轨迹的分钟数

# 5. 预测驱动预调度配置
DISPATCH_PRED_SEQ_LEN = 8
DISPATCH_PRED_PRE_LEN = 1
DISPATCH_PRED_VAL_DAYS = 1
BSTGCNET_DISPATCH_MAX_EPOCHS = 300
BSTGCNET_DISPATCH_PATIENCE = 50
MCTGNET_DISPATCH_MAX_EPOCHS = 3000
MCTGNET_DISPATCH_PATIENCE = 150
MCTGNET_DISPATCH_LR = 0.0005
MCTGNET_DISPATCH_LOG_INTERVAL = 20
MCTGNET_DISPATCH_REFIT_ON_ALL_PRETARGET = True
MCTGNET_DISPATCH_CENTER_LOSS_WEIGHT = 0.55
MCTGNET_DISPATCH_CENTER_HOTSPOT_ALPHA = 1.8
MCTGNET_DISPATCH_CENTER_UNDERPREDICT_ALPHA = 3.0
MCTGNET_DISPATCH_CENTER_UNDERPREDICT_POWER = 1.2
MCTGNET_DISPATCH_USE_ONLINE_ADAPTATION = True
MCTGNET_DISPATCH_ONLINE_BIAS_ALPHA = 0.30
MCTGNET_DISPATCH_ONLINE_SLOT_BIAS_ALPHA = 0.40
MCTGNET_DISPATCH_ONLINE_SCALE_ALPHA = 0.15
MCTGNET_DISPATCH_UQ_QUANTILE = 0.90
MCTGNET_DISPATCH_UQ_SLOT_BLEND = 0.65
MCTGNET_DISPATCH_UQ_ONLINE_ALPHA = 0.20
MCTGNET_DISPATCH_UQ_MIN_SIGMA_RATIO = 0.15
MCTGNET_DISPATCH_FORCE_CPU = False
MCTGNET_DISPATCH_USE_LSTM = True
MCTGNET_DISPATCH_LSTM_LAYERS = 1
MCTGNET_DISPATCH_LSTM_DROPOUT = 0.10
CENTER_LSTM_DISPATCH_SEQ_LEN = 32
CENTER_LSTM_DISPATCH_PRE_LEN = 1
CENTER_LSTM_DISPATCH_MAX_EPOCHS = 400
CENTER_LSTM_DISPATCH_PATIENCE = 60
CENTER_LSTM_DISPATCH_LR = 0.0005
CENTER_LSTM_DISPATCH_HIDDEN_DIM = 128
CENTER_LSTM_DISPATCH_LSTM_LAYERS = 2
CENTER_LSTM_DISPATCH_DROPOUT = 0.15
CENTER_LSTM_DISPATCH_LOG_INTERVAL = 20
CENTER_LSTM_DISPATCH_HOTSPOT_ALPHA = 2.5
CENTER_LSTM_DISPATCH_UNDERPREDICT_ALPHA = 3.0
CENTER_LSTM_DISPATCH_UNDERPREDICT_POWER = 1.0
CENTER_LSTM_DISPATCH_REFIT_ON_ALL_PRETARGET = True
CENTER_LSTM_DISPATCH_USE_ONLINE_ADAPTATION = True
CENTER_LSTM_DISPATCH_ONLINE_BIAS_ALPHA = 0.30
CENTER_LSTM_DISPATCH_ONLINE_SLOT_BIAS_ALPHA = 0.40
CENTER_LSTM_DISPATCH_ONLINE_SCALE_ALPHA = 0.15
MAX_TASKS_PER_WORKER = 4
PREDISPATCH_BACKLOG_WEIGHT = 1.0
PREDISPATCH_MIN_BUFFER_WORKERS = 1
PREDISPATCH_RESERVE_RATIO = 0.05
PREDISPATCH_MAX_SHARE_PER_DONOR = 0.55
# `None` means no hard cap on worker transfer distance during pre-dispatch.
PREDISPATCH_MAX_DISTANCE_KM = None
# Penalty for leaving a worker in an oversupplied center where they may idle.
PREDISPATCH_IDLE_PENALTY = 1.0
# Extra penalty for packing too many workers into the same center.
PREDISPATCH_CONGESTION_PENALTY = 0.45
# Bonus for borrowing workers that are already far from their current center.
PREDISPATCH_REMOTE_WORKER_BONUS = 0.05
PREDISPATCH_PEAK_WEIGHT = 0.25
PREDISPATCH_DEMAND_MARGIN = 0.08
GAME_DISPATCH_FAIRNESS_WEIGHT = 0.0
GAME_DISPATCH_DISTANCE_PENALTY = 0.003
GAME_DISPATCH_DONOR_MAX_UTILITY_DROP = 0.30
GAME_DISPATCH_RECEIVER_MIN_GAIN = 0.0
GAME_DISPATCH_MAX_ITERATIONS = 320
GAME_DISPATCH_BURST_OUTBOUND_SHARE = 0.90
GAME_DISPATCH_HIGH_DEMAND_MULTIPLIER = 1.05
GAME_DISPATCH_HIGH_DEMAND_SHORTAGE_RATIO = 0.15
GAME_DISPATCH_CANDIDATE_K = 20
GAME_DISPATCH_POTENTIAL_EPSILON = 0.0005

# Worker sampling for the fixed 06:55 snapshot used by the 07:00 batch.
# `None` means keep all workers from the snapshot.
EXPERIMENT_WORKER_LIMIT = 400
# Options:
# - "snapshot_global": sample directly from the full 06:55 snapshot pool
# - "per_region": sample as evenly as possible from each region's snapshot workers
#EXPERIMENT_WORKER_SAMPLING_MODE = "snapshot_global"
EXPERIMENT_WORKER_SAMPLING_MODE = "per_region"
EXPERIMENT_WORKER_SAMPLE_SEED = 42
EXPERIMENT_COMPARE_SLOT_COUNT = 8
PREDISPATCH_LOOKAHEAD_SLOTS = 2
PREDISPATCH_LOOKAHEAD_DECAY = 0.70

# Task-maximizing settings used only by Predictive-MCTGNet.
PREDICTIVE_PREDISPATCH_MIN_BUFFER_WORKERS = 0
PREDICTIVE_PREDISPATCH_RESERVE_RATIO = 0.0
PREDICTIVE_PREDISPATCH_MAX_SHARE_PER_DONOR = 0.80
PREDICTIVE_PREDISPATCH_IDLE_PENALTY = 1.15
PREDICTIVE_PREDISPATCH_CONGESTION_PENALTY = 0.25
PREDICTIVE_PREDISPATCH_REMOTE_WORKER_BONUS = 0.08
PREDICTIVE_PREDISPATCH_DISTANCE_PENALTY = 0.001
PREDICTIVE_PREDISPATCH_PEAK_WEIGHT = 0.20
PREDICTIVE_PREDISPATCH_DEMAND_MARGIN = 0.10

# 6. 不确定性感知双边博弈预调度配置
UABG_HISTORY_SIZE = 12
UABG_MOVE_HISTORY_SIZE = 8
UABG_BACKLOG_WEIGHT = 1.0
UABG_UNCERTAINTY_WEIGHT = 0.45
UABG_QUANTILE_WEIGHT = 0.55
UABG_BURST_WEIGHT = 1.2
UABG_MIN_BUFFER_WORKERS = 1
UABG_RESERVE_RATIO = 0.10
UABG_MAX_SHARE_PER_DONOR = 0.60
UABG_MAX_DISTANCE_KM = None
UABG_DONOR_SIGMA_BUFFER = 0.30
UABG_DONOR_TAIL_BUFFER = 0.40
UABG_DONOR_DEBT_BUFFER = 0.35
UABG_BID_SHORTAGE_WEIGHT = 0.90
UABG_BID_SERVICE_WEIGHT = 0.70
UABG_BID_BACKLOG_WEIGHT = 0.45
UABG_BID_BURST_WEIGHT = 0.60
UABG_BID_DEBT_WEIGHT = 0.85
UABG_ASK_SHORTAGE_WEIGHT = 0.85
UABG_ASK_FAIRNESS_WEIGHT = 0.70
UABG_ASK_UNCERTAINTY_WEIGHT = 0.65
UABG_DISTANCE_PENALTY = 0.004
UABG_OPPORTUNITY_ETA_WEIGHT = 0.015
UABG_OPPORTUNITY_CAPTURE_WEIGHT = 0.90
UABG_OPPORTUNITY_RETURN_WEIGHT = 0.06
UABG_REMOTE_WORKER_BONUS = 0.05
UABG_SWITCH_COOLDOWN_SLOTS = 2
UABG_SWITCH_RECENT_PENALTY = 0.60
UABG_SWITCH_REPEAT_PENALTY = 0.25
UABG_SWITCH_LOOKBACK_SLOTS = 4
UABG_CANDIDATE_K = 16
UABG_EDGE_EPSILON = 0.05
UABG_SERVICE_DEBT_DECAY = 0.85
UABG_MAX_SERVICE_DEBT = 4.0
